# Generated by Django 4.2.3 on 2023-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_ordering',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
