# Generated by Django 4.2.3 on 2023-07-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='author',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='author',
        ),
    ]
